version: "3"
services:
  mongodb:
    container_name: mongodb
    image: mongo
    ports:
      - "27017:27017"
  backend:
    build: ./backend
    ports:
      - "9000:9000"
    container_name: backend
    depends_on:
      - mongodb
    env_file:
    - ./backend/.env
  frontend:
    build: ./client
    ports:
      - "3000:3000"
    container_name: client

    stdin_open: true
    tty: true
